dist: xenial

language: python

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

env:
  global:
    - TEST_POSTGRES_PORT=5432

matrix:
  include:
    - python: 3.8
      env: TOXENV=black
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38

install:
  - pip install tox

script:
  - tox
